Vagrant.configure("2") do |config|

  config.berkshelf.enabled = false
  config.omnibus.chef_version = :latest
  config.chef_zero.enabled = true

  config.vm.define :centos6 do |centos6|
    centos6.vm.box      = 'opscode-centos-6.5'
    centos6.vm.box_url  = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box'
    centos6.vm.hostname = "centos65"
    centos6.vm.provision "shell", inline: "yum install -y http://mirror-fpt-telecom.fpt.net/fedora/epel/6/i386/epel-release-6-8.noarch.rpm;yum install -y python-pip;pip install boto;mkdir -p /etc/chef"
  end

  config.vm.define :saucy do |saucy|
    saucy.vm.box      = 'saucy'
    saucy.vm.box_url  = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'
    saucy.vm.hostname = "ubuntu"
    saucy.vm.provision "shell", inline: "apt-get install -y python-pip;pip install boto;mkdir -p /etc/chef"
  end

  config.vm.network :private_network, ip: '10.100.0.2'
  config.vm.network "forwarded_port", guest: 80, host: 8000

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.provision :chef_client do |chef|
    
    chef.log_level = :debug
    
    chef.json = {

    }
    
    chef.run_list = [
      "recipe[python::pip]",
      "recipe[devops-classday]"
    ]
    
  end
end
